// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ8TdxOh9Bw8sMDaWfQtDMIBvudWq6tUw',
    appId: '1:373547140871:web:ebd3a0f428b384a3a4a7a2',
    messagingSenderId: '373547140871',
    projectId: 'medical-guideline-bot',
    authDomain: 'medical-guideline-bot.firebaseapp.com',
    storageBucket: 'medical-guideline-bot.firebasestorage.app',
    measurementId: 'G-J5JK9JSFMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpzM_7nJ0IVOaGw21yusD8k6So653qN2s',
    appId: '1:373547140871:android:00f928374271b808a4a7a2',
    messagingSenderId: '373547140871',
    projectId: 'medical-guideline-bot',
    storageBucket: 'medical-guideline-bot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYcnSkmFn33xaTaoHTPYIz5SACgR19J2M',
    appId: '1:373547140871:ios:249f8d19c2b4bfc9a4a7a2',
    messagingSenderId: '373547140871',
    projectId: 'medical-guideline-bot',
    storageBucket: 'medical-guideline-bot.firebasestorage.app',
    iosBundleId: 'com.kaitech.medicalguideline',
  );
}
